/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.systex.sysgateii.ratesvr;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
